### ISSUE TITLE
Empty File behaviour

### ISSUE THREAD

**Issue by floriant** [sebastianbergmann/phpcpd#104]
I want to Use the phpcpd Command in addition to own Scripts. This makes use of the Return Value (example: exit(1)) to detect the general Result of the Check.

Tested with empty Directory:
Return: 1
No Files Detected Message

The Return Value 1 is representing Detected Errors according to:
src/CLI/Command.php
The Empty Check also returns 1. 

Solution: change to 2 for extra Check or to 0 according to No Errors found.

-------------------------------------------------------------------------------------------------------

Tested with Empty Text File Only:
Return: 0
100.00% duplicated lines out of 0 total lines of code.

Nothing seems to trigger a Duplicate, but triggers a Return 0 Code.
This can cause Problems on some Frameworks where Empty Files can be Part of a System.
For Example: Typo3 uses an empty ENABLE_INSTALL_TOOL File to allow Install Tool Access.
 
Solution: Extra Parse for empty Files. No Duplication -> No Error

**Comment by sebastianbergmann** [comment]
I am not convinced that this is useful, sorry.
