### ISSUE TITLE
PHP Warning:  file_put_contents()

### ISSUE THREAD

**Issue by youssefbenhssaien** [sebastianbergmann/phpcpd#110]
I got the php warning when i try to include --log-pmd option to an inexisting file, it rather use fopen() and fwrite() than use file_put_contents() to create the expected missing file
ex : vendor/phpcpd/phpcpd src/ --log-pmd app/Resources/pcd/projectPhpcpd.xml
pcd/projectPhpcpd.xml file doesn't exist

**Comment by TomAdam** [comment]
It is the the directory that doesn't exist rather than the file. Creating it should solve the issue.
