### ISSUE TITLE
Report average and maximum length of code clone

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpcpd#117]

**Comment by CoreylDagget** [comment]
#158
quick and dirty but sufficent.
want another formating or is everything fine for you?

Testet with private code and Wordpress

**Comment by niconoe-** [comment]
It looks like this is done in the current version: https://github.com/sebastianbergmann/phpcpd/blob/951cfbef34cae20370d6a9aebcf834d2aa012864/src/Log/Text.php#L61

Do you still have related ideas in mind that are not described here?
