### ISSUE TITLE
Hacklang CPD?

### ISSUE THREAD

**Issue by skyzyx** [sebastianbergmann/phpcpd#118]
Is there an interest in, or work underway to, implement support for Hack in addition to PHP?

**Comment by sebastianbergmann** [comment]
No.

**Comment by aboks** [comment]
Actually, Hacklang is already supported out-of-the-box when running PHPCPD on HHVM. PHPCPD uses `token_get_all` for tokenizing the source files, which can also tokenize Hacklang in its implementation on HHVM.  Maybe it misses just a bit of intelligence (fuzzing) for Hacklang-specific tokens, but the basics should work just fine.

For doing Hacklang-CPD on PHP, #83 may be a (small) step in that direction. However, it would still require finding or implementing a Hacklang-tokenizer in plain PHP.
