### ISSUE TITLE
PHPCPDTask depends on PHPCPD being installed and on include_path

### ISSUE THREAD

**Issue by amelaye** [sebastianbergmann/phpcpd#120]
Hi, 
I'm one of the few people who had this error.
I had installed phpcpd and Phing to do some continous integration on Jenkins.

So I had put my XML command on my builder.xml :

`<target name="phpcpd">`
`<phpcpd file="${project.basedir}/${source}">`
`<formatter type="pmd" outfile="${project.basedir}/build/logs/pmd-cpd.xml"/>`
`</phpcpd>`
`</target>`

But on building, Jenkins gets this issue :

TestJenkins > phpcpd:

Execution of target "phpcpd" failed for the following reason: /var/lib/jenkins/workspace/intranet/utils/build/build.xml:45:18: /var/lib/jenkins/workspace/intranet/utils/build/build.xml:45:18: PHPCPDTask depends on PHPCPD being installed and on include_path.
[phingcall] /var/lib/jenkins/workspace/intranet/utils/build/build.xml:45:18: /var/lib/jenkins/workspace/intranet/utils/build/build.xml:45:18: PHPCPDTask depends on PHPCPD being installed and on include_path.
Execution of target "qa" failed for the following reason: /var/lib/jenkins/workspace/intranet/utils/build/build.xml:25:23: Execution of the target buildfile failed. Aborting.

What's the problem ? i saw this : https://www.phing.info/trac/ticket/1061 but I couldn't find the class PHPCPDTask in the source code.

Thanks

**Comment by sebastianbergmann** [comment]
Please use the Phing issue tracker for issues related to Phing.
