### ISSUE TITLE
Use statements for namespaces seem to be included as tokens for CPD

### ISSUE THREAD

**Issue by Gisleburt** [sebastianbergmann/phpcpd#128]
PHPCPD 2.0.2. This seems to be related to #71 

Output:

``` bash
$ vendor/bin/phpcpd src --min-tokens=55
phpcpd 2.0.2 by Sebastian Bergmann.

Found 1 exact clones with 32 duplicated lines in 2 files:

  - /Users/daniel.mason/Documents/Projects/Masonry/src/Workers/Group/Parallel/Worker.php:14-46
    /Users/daniel.mason/Documents/Projects/Masonry/src/Workers/Group/Serial/Worker.php:14-46

0.94% duplicated lines out of 3399 total lines of code.

Time: 108 ms, Memory: 4.00Mb
```

Snippets showing repeated code:

**Parallel**: [src/Workers/Group/Parallel/Worker.php:14-46](https://github.com/TheFoundryVisionmongers/Masonry/blob/release/1.0.0-alpha.1/src/Workers/Group/Parallel/Worker.php#L14-L46)

``` php
use Foundry\Masonry\Core\CoroutineRegister;
use Foundry\Masonry\Core\Notification;
use Foundry\Masonry\Interfaces\Pool\StatusInterface as PoolStatusInterface;
use Foundry\Masonry\Interfaces\Task\StatusInterface as TaskStatusInterface;
use Foundry\Masonry\Interfaces\TaskInterface;
use Foundry\Masonry\Workers\Group\AbstractGroupWorker;
use React\Promise\Deferred;
/**
 * Class Worker
 *
 * @package Masonry
 * @see     https://github.com/Visionmongers/
 */
class Worker extends AbstractGroupWorker
{
    /**
     * Where the actual work is done
     * @param Deferred $deferred
     * @param TaskInterface $task
     * @return mixed
     */
    protected function processDeferred(Deferred $deferred, TaskInterface $task)
    {
        yield;
        /** @var Description $pool */
        $pool = $task->getDescription();
        try {
            $deferred->notify(Notification::normal('Processing serial task group'));
```

**Serial**:  [src/Workers/Group/Serial/Worker.php:14-46](https://github.com/TheFoundryVisionmongers/Masonry/blob/release/1.0.0-alpha.1/src/Workers/Group/Serial/Worker.php#L14-L46)

``` php
use Foundry\Masonry\Core\CoroutineRegister;
use Foundry\Masonry\Core\Notification;
use Foundry\Masonry\Interfaces\Pool\StatusInterface as PoolStatusInterface;
use Foundry\Masonry\Interfaces\Task\StatusInterface as TaskStatusInterface;
use Foundry\Masonry\Interfaces\TaskInterface;
use Foundry\Masonry\Workers\Group\AbstractGroupWorker;
use React\Promise\Deferred;
/**
 * Class Worker
 *
 * @package Masonry
 * @see     https://github.com/Visionmongers/
 */
class Worker extends AbstractGroupWorker
{
    /**
     * Where the actual work is done
     * @param Deferred $deferred
     * @param TaskInterface $task
     * @return mixed
     */
    protected function processDeferred(Deferred $deferred, TaskInterface $task)
    {
        yield;
        /** @var Description $pool */
        $pool = $task->getDescription();
        try {
            $deferred->notify(Notification::normal("Processing parallel task group"));
```

While the lines are clearly the same, there isn't a way (that I can see) to unify it. The problem really seems to be that the "use" statements are counted in the number of concurrent tokens.

**Comment by sebastianbergmann** [comment]
Since a3de63fb915f39eba3878ea436e242dd4e86f3f3 the `T_USE` token is ignored thus the problem should be solved.

Do you still experience the problem in the current version of PHPCPD? Thanks!

**Comment by sebastianbergmann** [comment]
I cannot reproduce this:

```
$ cat A.php 
<?php
use Foundry\Masonry\Core\CoroutineRegister;
use Foundry\Masonry\Core\Notification;
use Foundry\Masonry\Interfaces\Pool\StatusInterface as PoolStatusInterface;
use Foundry\Masonry\Interfaces\Task\StatusInterface as TaskStatusInterface;
use Foundry\Masonry\Interfaces\TaskInterface;
use Foundry\Masonry\Workers\Group\AbstractGroupWorker;
use React\Promise\Deferred;
```
```
$ cat B.php
<?php
use Foundry\Masonry\Core\CoroutineRegister;
use Foundry\Masonry\Core\Notification;
use Foundry\Masonry\Interfaces\Pool\StatusInterface as PoolStatusInterface;
use Foundry\Masonry\Interfaces\Task\StatusInterface as TaskStatusInterface;
use Foundry\Masonry\Interfaces\TaskInterface;
use Foundry\Masonry\Workers\Group\AbstractGroupWorker;
use React\Promise\Deferred;
```
```
$ /usr/local/src/phpcpd/phpcpd .
phpcpd 3.0-g5f5ebbb by Sebastian Bergmann.

0.00% duplicated lines out of 18 total lines of code.

Time: 21 ms, Memory: 2.00MB
```

**Comment by deranga** [comment]
Hi, 

I seem to still be experiencing the issue addressed by this commit. phpcpd still seems to pick up the USE keyword ?

vendor/bin/phpcpd --min-lines 3 --min-tokens 55 ./src
phpcpd 4.1.0 by Sebastian Bergmann.

Found 1 clones with 14 duplicated lines in 2 files:

  - ..../src/Normalizer/UserFieldNormalizer.php:8-22 (14 lines)
    ..../src/Normalizer/UserFieldValueNormalizer.php:9-23

0.39% duplicated lines out of 3613 total lines of code.
Average size of duplication is 14 lines, largest clone has 14 of lines

Time: 78 ms, Memory: 6.00MB
cat -n src/Normalizer/UserFieldNormalizer.php 
     1	<?php
     2	
     3	        namespace App\Normalizer;
     4	
     5	        use App\Entity\Field;
     6	        use App\Entity\UserField;
     7	        use App\Entity\UserFieldValue;
     8	        use App\Repository\FieldRepository;
     9	        use Doctrine\Common\Collections\ArrayCollection;
    10	use Symfony\Component\Serializer\Exception\BadMethodCallException;
    11	use Symfony\Component\Serializer\Exception\ExtraAttributesException;
    12	use Symfony\Component\Serializer\Exception\InvalidArgumentException;
    13	use Symfony\Component\Serializer\Exception\LogicException;
    14	use Symfony\Component\Serializer\Exception\RuntimeException;
    15	use Symfony\Component\Serializer\Exception\UnexpectedValueException;
    16	use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
    17	use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
    18	use Symfony\Component\Serializer\SerializerAwareInterface;
    19	use Symfony\Component\Serializer\SerializerAwareTrait;


cat -n src/Normalizer/UserFieldValueNormalizer.php
     1	<?php
     2	
     3	        namespace App\Normalizer;
     4	
     5	        use App\Entity\Field;
     6	        use App\Entity\UserField;
     7	        use App\Entity\UserFieldValue;
     8	        use App\Entity\UserFieldValueString;
     9	        use App\Repository\FieldRepository;
    10	use Doctrine\Common\Collections\ArrayCollection;
    11	use Symfony\Component\Serializer\Exception\BadMethodCallException;
    12	use Symfony\Component\Serializer\Exception\ExtraAttributesException;
    13	use Symfony\Component\Serializer\Exception\InvalidArgumentException;
    14	use Symfony\Component\Serializer\Exception\LogicException;
    15	use Symfony\Component\Serializer\Exception\RuntimeException;
    16	use Symfony\Component\Serializer\Exception\UnexpectedValueException;
    17	use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
    18	use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
    19	use Symfony\Component\Serializer\SerializerAwareInterface;
    20	use Symfony\Component\Serializer\SerializerAwareTrait;

great tool BTW!

Thanks

Lee
