### ISSUE TITLE
mbstring.internal_encoding is deprecated 

### ISSUE THREAD

**Issue by torkiljohnsen** [sebastianbergmann/phpcpd#129]
Deprecated: ini_set(): Use of mbstring.internal_encoding is deprecated in /my/path/vendor/sebastian/phpcpd/phpcpd on line 47
phpcpd 2.0.1 by Sebastian Bergmann.

> This feature has been DEPRECATED as of PHP 5.6.0. Relying on this feature is highly discouraged.
> PHP 5.6 and later users should leave this empty and set default_charset instead.

**Comment by Shnoulle** [comment]
https://github.com/sebastianbergmann/phpcpd/issues/97 fixed in https://github.com/sebastianbergmann/phpcpd/commit/bce5d0345f10d29801b0f4acc65491896a25c80e
