### ISSUE TITLE
v2.0.2 not installable with Symfony 3

### ISSUE THREAD

**Issue by peterrehm** [sebastianbergmann/phpcpd#130]
Version 2.0.2 is not installable with Symfony 3 while 2.0.1 is installable with Symfony 3.
This is already fixed in the latest composer.json and should just require a new release to be fixed.

**Comment by sebastianbergmann** [comment]
Thank you for bringing this to my attention. "Stupid" issues like this one are the reason why I suggest using tools from PHP archives (PHAR).

**Comment by peterrehm** [comment]
Thanks for the prompt "fix" :)
