### ISSUE TITLE
The helper "progress" is not defined

### ISSUE THREAD

**Issue by nnnikolay** [sebastianbergmann/phpcpd#132]
Hi,

I've used phpcpd within phing long long time

```
<target name="phpcpd-dev"
                description="Copy/Paste Detector (CPD) for PHP code"
                depends="init">
            <exec passthru="true"
                  command="${php.bin.path}/phpcpd --progress --ansi --fuzzy ${project.sitedir}" />
        </target>
```

but recently I did an upgrade my project's dependencies and it seems phpcpd 2.0.4 was installed.
now it does not work :(

```
  [Symfony\Component\Console\Exception\InvalidArgumentException]  
  The helper "progress" is not defined.                           
```

Sure it works If I'll get rid of `--progress`

I've checked phpcpd's composer.json and symfony/console is there.. 
Here is my project composer.json

```
},
    "require-dev": {
        ...
        "sebastian/phpcpd": "*",
        ...
    },
```

I'm not sure is it a bug or not :)

**Comment by tomzx** [comment]
It appears this is already "fixed" in the master version.

@2.0.4
```
$progressHelper = $this->getHelperSet()->get('progress');
```

@sebastianbergmann 
```
$progressBar = new ProgressBar($output, count($files));
```

**Comment by sebastianbergmann** [comment]
I cannot reproduce this in `master`.
