### ISSUE TITLE
ERROR: The certificate of ‘phar.phpunit.de’ is not trusted.

### ISSUE THREAD

**Issue by andreustimm** [sebastianbergmann/phpcpd#133]
I run... **wget https://phar.phpunit.de/phpcpd.phar**

--2016-06-24 12:00:09--  https://phar.phpunit.de/phpcpd.phar
Resolving phar.phpunit.de (phar.phpunit.de)... 188.94.27.25
Connecting to phar.phpunit.de (phar.phpunit.de)|188.94.27.25|:443... connected.
**ERROR: The certificate of ‘phar.phpunit.de’ is not trusted.
ERROR: The certificate of ‘phar.phpunit.de’ hasn't got a known issuer.**

**Comment by sebastianbergmann** [comment]
I cannot reproduce this:
```
$ wget https://phar.phpunit.de/phpcpd.phar
--2016-06-25 08:32:58--  https://phar.phpunit.de/phpcpd.phar
Resolving phar.phpunit.de (phar.phpunit.de)... 188.94.27.25
Connecting to phar.phpunit.de (phar.phpunit.de)|188.94.27.25|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://phar.phpunit.de/phpcpd-2.0.4.phar [following]
--2016-06-25 08:32:59--  https://phar.phpunit.de/phpcpd-2.0.4.phar
Reusing existing connection to phar.phpunit.de:443.
HTTP request sent, awaiting response... 200 OK
Length: 562070 (549K) [application/octet-stream]
Saving to: ‘phpcpd.phar’

phpcpd.phar         100%[===================>] 548.90K   709KB/s    in 0.8s    

2016-06-25 08:33:00 (709 KB/s) - ‘phpcpd.phar’ saved [562070/562070]
```

**Comment by pasanmdev** [comment]
Hi
Looks like site certs are expired? though I can access it from browser

wget https://phar.phpunit.de/phpcpd.phar
--2021-11-19 14:04:57--  https://phar.phpunit.de/phpcpd.phar
Resolving phar.phpunit.de (phar.phpunit.de)... 188.94.27.25
Connecting to phar.phpunit.de (phar.phpunit.de)|188.94.27.25|:443... connected.
ERROR: The certificate of ‘phar.phpunit.de’ is not trusted.
ERROR: The certificate of ‘phar.phpunit.de’ has expired.

**Comment by sebastianbergmann** [comment]
I cannot reproduce this:

```
$ wget https://phar.phpunit.de/phpcpd.phar    
--2021-11-19 06:37:21--  https://phar.phpunit.de/phpcpd.phar
Resolving phar.phpunit.de (phar.phpunit.de)... 188.94.27.25
Connecting to phar.phpunit.de (phar.phpunit.de)|188.94.27.25|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://phar.phpunit.de/phpcpd-6.0.3.phar [following]
--2021-11-19 06:37:21--  https://phar.phpunit.de/phpcpd-6.0.3.phar
Reusing existing connection to phar.phpunit.de:443.
HTTP request sent, awaiting response... 200 OK
Length: 70780 (69K) [application/octet-stream]
Saving to: ‘phpcpd.phar’

phpcpd.phar         100%[==================>]  69.12K  --.-KB/s    in 0.04s   

2021-11-19 06:37:21 (1.84 MB/s) - ‘phpcpd.phar’ saved [70780/70780]
```

**Comment by pasanmdev** [comment]
@sebastianbergmann all good, I tested it in the latest debian and was able to download it. probably old ca issues on my old image

**Comment by wildwind123** [comment]
On docker got same error. I can fix it with this option
--no-check-certificate.   Example 
wget --no-check-certificate -O phpunit https://phar.phpunit.de/phpunit-9.phar
