### ISSUE TITLE
Exception: LineStart must be an integer

### ISSUE THREAD

**Issue by Ooypunk** [sebastianbergmann/phpcpd#134]
Hello,
Used within PHPCI, my CPD keeps crashing, and I would like to know why.
The output I get is:

```
phpcpd 2.0.4 by Sebastian Bergmann.
Found 2 exact clones with 32 duplicated lines in 1 files:
  -	/application/libraries/minify/cssmin-v3.0.1.php:445-468
 	/application/libraries/minify/cssmin-v3.0.1.php:1716-1739
 
  -	/application/libraries/minify/cssmin-v3.0.1.php:491-500
 	/application/libraries/minify/cssmin-v3.0.1.php:1756-1765
 
0.36% duplicated lines out of 8781 total lines of code.
Time: 373 ms, Memory: 28.00MB
Uitzondering:LineStart must be an integer.
PLUGIN: FAILED
```

Did the plugin fail because of the exception, or because it found these 2 duplicate code blocks?

Only argument for CPD is:
```
standard: "PSR2"
```

**Comment by aboks** [comment]
This is probably not a bug in PHPCPD, but one in the CPD-plugin for PHPCI. There is already a pull request with a fix: https://github.com/Block8/PHPCI/pull/1201.

**Comment by Ooypunk** [comment]
The fix works like a charm! Thanks for the speedy answer!
