### ISSUE TITLE
Support for @ignoreDuplicates

### ISSUE THREAD

**Issue by vbashkirtsev** [sebastianbergmann/phpcpd#136]
Some code generation tools we use in our work generate number of similarly structured PHP files. As these files are automatically generated they are full of duplicates and CPD analysis against these files does not make sense. We have used command line --exclude option to exclude these files but now there's large number of such files and listing them on command line is no longer viable. It would be really good if PHPCPD would honor tag @ignoreDuplicates (or similarly named) in file level docblock and skip such file outright.

Should it be considered as improvement? I am willing to contribute appropriate PR. Just want to ensure acceptance before spending time on this.

**Comment by roperto** [comment]
I think the ability to suppress warnings is very important.

I had similar problems and reached this page looking for a way to suppress warnings for a method (possibly a class or whole file).

**Comment by sebastianbergmann** [comment]
I think it would be better to simply exclude such files from the process and do not point PHPCPD to them.
