### ISSUE TITLE
Generate JSON report

### ISSUE THREAD

**Issue by quentincurtet** [sebastianbergmann/phpcpd#137]
Hi,

I'm using the latest version of PHPCPD, but i can't use the command line to generate json report for duplicated code.

Is it possible or not yet ?

Best regards.

**Comment by quentincurtet** [comment]
Any update ?

**Comment by sebastianbergmann** [comment]
I am not interested in JSON and will not implement a JSON-based logger for PHPCPD. I would, of course, consider a pull request that implements this.
