### ISSUE TITLE
Collaboration with Codacy

### ISSUE THREAD

**Issue by machadoit** [sebastianbergmann/phpcpd#140]
Hi there, João Machado from [Codacy](https://www.codacy.com) here.

We have a PHPCPD integration, so that everyone that uses our website can get PHP duplication analysis. You can check it at https://github.com/codacy/codacy-duplication-phpcpd.

Would you guys be interested on mentioning us as proud users of PHPCPD? You can also add your PHPCPD at [Codacy](https://www.codacy.com) to check it out, we are free for open source projects.

**Comment by sebastianbergmann** [comment]
PHPCPD does not have a website so there is no place where we could mention Codacy.
