### ISSUE TITLE
Add support for configuration file

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpcpd#141]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpcpd
    strategy="SebastianBergmann\PHPCPD\Detector\Strategy\DefaultStrategy"
    minimumLines="5"
    minimumTokens="70"
    fuzzy="true">

    <fileset>
        <include>
            <directory>foo</directory>
            <file>bar.phtml</file>
        </include>
        <exclude>bar</exclude>
        <name>*.php</name>
        <notName>*.fail.php</notName>
    </fileset>

    <logging>
        <log type="pmd" target="pmd-cpd.xml"/>
        <log type="text" target="cpd.txt"/>
    </logging>
</phpcpd>
```

**Comment by hoaiphongt** [comment]
- Hi, i'm using phpcpd to check my codes. But i would like to config statics like this config. where do i put this file in my source and what's name ?. Thank you

**Comment by dmaciej** [comment]
@sebastianbergmann are you going to add this feature soon? It would be very helpful for my projects if I could ignore some directories.

**Comment by attiks** [comment]
Would be great if it uses the same param names as phpcs/phpmd like `<exclude-pattern>`

**Comment by pszalko** [comment]
@sebastianbergmann Do you have any estimate for implementing this feature?
