### ISSUE TITLE
Issue when  $file = current($this->files); return empty

### ISSUE THREAD

**Issue by jnurit** [sebastianbergmann/phpcpd#145]
An issue occurred when current($this->files) return an empty value. Please, add a test for that.
The issue : Fatal error: Call to a member function getName() on boolean in phar:///usr/local/bin/phpcpd/src/CodeClone.php on line 106

if i use :
            if($file) {
                $this->lines = implode(
                    '',
                    array_map(
                        function ($line) use ($indent) {
                            return $indent . $line;
                        },
                        array_slice(
                            file($file->getName()),
                            $file->getStartLine() - 1,
                            $this->size
                        )
                    )
                );
            }

It's ok. I tied to make a pull request, but don't work.

A great "thank you" for your work !

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
