### ISSUE TITLE
Duplicated lines not being detected

### ISSUE THREAD

**Issue by zagrad** [sebastianbergmann/phpcpd#149]
So the following code is not being detected as code duplication. Is that a bug, or do I not understand the purpose of this tool?

    <?php

    print('So this line might be there again');
    print('As well as this line...');
    
    echo "Do something else";
    print('So this line might be there again');
    print('As well as this line...');
    
    die('-- the end');

**Comment by aboks** [comment]
This is because PHPCPD only reports duplications that exceed a given number of lines (default 5) and a given number of tokens (default 70). See the `--min-lines` and `--min-tokens` command line options.

**Comment by sebastianbergmann** [comment]
Thanks for the explanation, @aboks.
