### ISSUE TITLE
New release? Symfony Console component version related.

### ISSUE THREAD

**Issue by HugoMestre** [sebastianbergmann/phpcpd#150]
This [commit](https://github.com/sebastianbergmann/phpcpd/commit/cff7f36c2ae89d59987de25d14fd41a72dd4a703) isn't present in a release yet. Maybe it should because it would be easier to require PHPCPD through composer when running a previous version on the [symfony/console](https://github.com/symfony/console) component.

**Comment by sebastianbergmann** [comment]
phpcpd 3.0.1 has been released.
