### ISSUE TITLE
Please loosen version requirement

### ISSUE THREAD

**Issue by jurgenhaas** [sebastianbergmann/phpcpd#152]
This is an issue with dependency requirements incompatibility. Your package sebastian/phpcpd requires sebsatian/version `^2` which differs from the 1.x version only with regard to the PHP version requirement and some smaller code improvements.

My problem is, coming from the Drupal community, that I would like to use e.g. dealerdirect/qa-tools which requires sebastian/phpcpd and therefore requires sebastian/version `^2`. Drupal itself (as of Drupal 8.5.x) requires phpunit >=4.8.5 < 5, and, as previously mentioned, phpunit 4.x requires sebastian/version ^1.

Unfortunately, in Drupal projects these tools can't be used.

As a solution I wonder if you were able to change the version requirement here in sebastian/phpcpd for sebastian/version to `^1 | ^2`. That would allow all projects that still require phpunit <5 to also use a lot of other packages that also utilize your amazing tools.

**Comment by sebastianbergmann** [comment]
You can always use `phpcpd` (and other tools) from a PHP archive.

**Comment by jurgenhaas** [comment]
Sure, but within a composer based workflow with a component that requires version 2 and another one requiring version 1 you're kind of stuck, aren't you?

**Comment by sebastianbergmann** [comment]
That is one of the reasons why I do not think that using Composer to manage tools is a good practice. Anyway, that is probably beside the point of this issue.

**Comment by jurgenhaas** [comment]
There might be issues but also benefits, i.e. having qa tools per project and shared with the team of developers. You're right, that discussion is not for here though.

Any chance you would consider the change of required versions for sebastion/version? I mean, it wouldn't change anything for existing installations as they would stay with version 2 anyways.
