### ISSUE TITLE
Tagging new version based on commit 'Cleanup'

### ISSUE THREAD

**Issue by hantc** [sebastianbergmann/phpcpd#157]
Hi,

this line broke our builds: 

https://github.com/sebastianbergmann/phpcpd/commit/bb7953b81fb28e55964d76d5fe2dbe725d43fab3#diff-76ada45d0f6fca50d54fd46ba813d9fdR167

therefore I had to change ^2.0 version in composer to dev-master to get actual code.

Could you please tag it as a new version?

Btw - error was: `PHP Fatal error:  Uncaught Error: Class 'PHP_Timer' not found in C:\web\project\vendor\sebastian\phpcpd\src\CLI\Command.php:164`

Thanks

**Comment by sebastianbergmann** [comment]
I do not understand the issue you are trying to report.

**Comment by hantc** [comment]
Issue is that your latest release references to PHP_Timer which no longer exists. Therefore we're not able to use it and we are forced to download your package via `dev-master` composer property :)

**Comment by sebastianbergmann** [comment]
The latest release is `4.0.0` and does not reference `PHP_Timer`:
```
$ git clone git@github.com:sebastianbergmann/phpcpd.git
Cloning into 'phpcpd'...
remote: Counting objects: 1777, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 1777 (delta 4), reused 18 (delta 2), pack-reused 1743
Receiving objects: 100% (1777/1777), 1.50 MiB | 1.93 MiB/s, done.
Resolving deltas: 100% (914/914), done.

$ cd phpcpd

$ git checkout 4.0.0
Note: checking out '4.0.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at bb7953b... Cleanup

$ ack PHP_Timer
```
The release before `4.0.0` was `3.0.1` and references `PHP_Timer`:
```
$ git checkout 3.0.1
Previous HEAD position was bb7953b... Cleanup
HEAD is now at dfed51c... Prepare release

$ ack PHP_Timer     
src/CLI/Command.php
166:            print \PHP_Timer::resourceUsage() . "\n";
```

**Comment by hantc** [comment]
Oh, mystery revealed.

![image](https://user-images.githubusercontent.com/11539237/36737017-4f68e32a-1bda-11e8-859d-0e778cf56533.png)

Sorry for bothering you and thanks a lot.

**Comment by NicoHaase** [comment]
FYI: I'm running in the same problem, having phpcpd v2.0.1 and phpunit/php-timer v2.1.2 installed. That later version of php-timer does not contain PHP_Timer anymore, but that old version of phpcpd is the latest one that is working with Symfony 5 due to very relaxed version constraints :(
