### ISSUE TITLE
Add support for nullable type declarations

### ISSUE THREAD

**Issue by ossinkine** [sebastianbergmann/phpcpd#162]
The following functions are detected as copy-pasted but their signatures are different:
```php
<?php

function foo(?string $foo): ?string
{
    return $foo;
}
```
```php
<?php

function foo(string $foo): string
{
    return $foo;
}
```

**Comment by 1blankz7** [comment]
I have create a PR for this issue but I think this is only a hack. Please see into the PR for more information.

**Comment by sebastianbergmann** [comment]
I cannot reproduce this:

```
$ cat /tmp/example/a.php 
<?php
function foo(?string $foo): ?string
{
    return $foo;
}
```
```
$ cat /tmp/example/b.php
<?php
function foo(string $foo): string
{
    return $foo;
}
```
```
$ phpcpd /tmp/example
phpcpd 4.1.0 by Sebastian Bergmann.

No clones found.

Time: 19 ms, Memory: 2.00MB
```

**Comment by ossinkine** [comment]
@sebastianbergmann Try to decrease min lines and tokens: `--min-lines=2 --min-tokens=5`

**Comment by ossinkine** [comment]
This issue is still reproduced

**Comment by ossinkine** [comment]
This issue is still reproduced

**Comment by ostrolucky** [comment]
Stalebot is ridiculous. And there is already plenty unresolved issues closed by stalebot.

**Comment by sebastianbergmann** [comment]
The bot only does what I told it to do.

**Comment by sebastianbergmann** [comment]
I do not think there is anything we can/should do here.
