### ISSUE TITLE
Alternative output

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpcpd#167]
Table with the files that contain duplicated code. For each file, show the percentage of lines in the file that are duplicated as well as the number of lines that are duplicated.

```
filename | duplicated lines % | duplicated lines
```

Sorted by `duplicated lines %s` (descending).

**Comment by niconoe-** [comment]
Current text output is containing lots of similar information. IMO it only misses the `duplicated lines %` data, which could be added to the number of duplicated lines in parenthesis, like

```
Found 1 code clones with 59 duplicated lines in 1 files:

  - /home/giraud30/Projects/GitHub/niconoe-/phpcpd/tests/fixture/Math.php:75-134 (59 lines, xx%)
    /home/giraud30/Projects/GitHub/niconoe-/phpcpd/tests/fixture/Math.php:139-198
```

What do you think about?

**Comment by sebastianbergmann** [comment]
This is not primarily about adding the "duplicated lines %" data, but about the sorting and table format.
