### ISSUE TITLE
Wrong duplicated lines are detected

### ISSUE THREAD

**Issue by nauxliu** [sebastianbergmann/phpcpd#171]
I saw a wrong duplicated report in our company project,

```
 - /A.php:53-174 (121 lines)
   /A.php:58-179
```

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by nauxliu** [comment]
## Environment:

PHP: 7.3.8
PHPCPD: 4.1.0
OS: Mac OS 10.14.5

## Command
```
php -d memory_limit=-1 A.php --fuzzy --min-tokens=50
```

## Code
A.php:

```
<?php

declare(strict_types=1);

final class Test implements Arrayable
{
    public $model;
    public $projection_info;
    public $family_info;
    public $income_assumptions;
    public $expense_assumptions;
    public $extra_debt_payment;
    public $tax;
    public $saving_strategy;
    public $invested_asset;
    public $asset_allocation_return_and_volatility_assumptions;
    public $annuity;
    public $withdrawal;
    public $loan;
    public $home;
    public $business_and_other_asset;
    public $options;
    public $insurance;
    public $trust;
    public $social_security;
    public $financial_goals;
    public $estate;
    public $inflation_rates;
    public $misc_items;
    public $override;
    public $scenario;
    public $retirement_spending_reduction_override;
}
```

**Comment by sebastianbergmann** [comment]
You are using `--fuzzy`. This effectively tells PHPCPD to replace all variable names with a fixed one. This is working as it is supposed to work.

**Comment by fabriciojs** [comment]
We are experiencing the same situation of a "false positive" also with a long list of member variables in a class definition.

![image](https://user-images.githubusercontent.com/1116377/108583230-d9791d00-7316-11eb-9d80-7334ace980ee.png)

@sebastianbergmann would it make sense to think that intersecting ranges should not be considered duplicates? Or at least have a threshold for intersecting ranges share to be disregarded or be considered as duplicate.
