### ISSUE TITLE
phpcpd and phploc confilct finder-facade

### ISSUE THREAD

**Issue by pyvm** [sebastianbergmann/phpcpd#177]
Hi ,
Its impossible to use `phpcpd` with `phploc` in the same pipeline because `phpcpd` need finder-face 2
but `phploc` want stability version of finder-face

**Comment by sebastianbergmann** [comment]
IMHO, a tool such as PHPCPD should not be installed using Composer but rather be used from a PHAR.

Eventually, there will be new releases of PHPCPD etc. that will solve this issue for Composer-based usage. But this is not a priority for me right now.
