### ISSUE TITLE
Compatibility with Symfony 5

### ISSUE THREAD

**Issue by NicoHaase** [sebastianbergmann/phpcpd#178]
Installing phpcpd using Composer is currently not possible when Symfony 5 is used, as there is no released version allowing this: the currently released version requires symfony/console in at most v4.0, which conflicts with symfony/console v5.

**Comment by sebastianbergmann** [comment]
I currently do not have time to work on this. I do not recommend using Composer to install this tool anyway, simply use the PHAR in the meantime.

**Comment by NicoHaase** [comment]
Thank your for that clarification, and after all thank you for your great work for the whole community!
