### ISSUE TITLE
Add support with xdebug 3.0.0

### ISSUE THREAD

**Issue by rcovar00** [sebastianbergmann/phpcpd#191]
Xdebug released 3.0.0 version were function xdebug_disable() was removed.

- Implemented issue #1868: Remove xdebug_disable and xdebug_enabled
https://pecl.php.net/package-changelog.php?package=xdebug

`xdebug_disable()` is used in `src/CLI/Application.php`

**Comment by sebastianbergmann** [comment]
[There is no Xdebug-specific code in this repository.](https://github.com/sebastianbergmann/phpcpd/search?q=xdebug)

**Comment by rcovar00** [comment]
Please check https://github.com/sebastianbergmann/phpcpd/commit/78ca17fd5fbd21e6b4583b8c2b70d1a975e2064e.

The function `disableXdebug()` is executing `xdebug_disable()`

https://xdebug.org/docs/upgrade_guide
According to Xcode 3.0.0 documentation xdebug_disable was removed 
![image](https://user-images.githubusercontent.com/11095885/101179384-c1470b00-360f-11eb-8160-7362b309322a.png)

**Comment by discordier** [comment]
@rcovar00: the function got removed in 98cc5f2c1fbdc8a0a43de23e176f3be64e9a3cd6 (and therefore is not in phpunit since late August or, to put it in versions, since 6.0)
