### ISSUE TITLE
Add option for wildcard exclude

### ISSUE THREAD

**Issue by Aerzas** [sebastianbergmann/phpcpd#193]
The exclude argument seems to expect complete paths (absolute or relative) which may create a very verbose command in modular codebases (Drupal in our case). It could be much more convenient to provides a path with wildcard rather than an exhaustive list of paths.

**Comment by niconoe-** [comment]
Untested but looking at the code, it seems it's now the case:

The `--exclude` option is given to the FileIterator\Facade where it is directly treated with a `glob`, where the wildcards are accepted. See https://github.com/sebastianbergmann/php-file-iterator/blob/543e7326a62c5e2060c508c10fdd746b646c687a/src/Factory.php#L72

Btw @sebastianbergmann maybe this method could be improved as for each folder definitions, you're doing an array_merge, while you could do a single one no matter how much folders there's in the list:

```php
    private function pathsAfterResolvingWildcards(array $paths): array
    {
        $_paths = [[]];

        foreach ($paths as $path) {
            if ($locals = glob($path, GLOB_ONLYDIR)) {
                $_paths[] = array_map('\realpath', $locals);
            } else {
                $_paths[] = [realpath($path)];
            }
        }

        return array_filter(array_merge(...$_paths));
    }
```

Got this from kalessil's best practices: https://kalessil.github.io/phpinspectionsea/docs/performance.html

**Comment by Aerzas** [comment]
I can confirm the wildcard is now working, thank you for the heads-up :)
