### ISSUE TITLE
Baseline for existing violations

### ISSUE THREAD

**Issue by kalinowski5** [sebastianbergmann/phpcpd#195]
Would be possible to implement Baseline feature like PHPStan and PHPMD currently have?

> PHPStan allows you to declare the currently reported list of errors as “the baseline” and cause it not being reported in subsequent runs. It allows you to be interested in violations only in new and changed code.

> It works best when you want to get rid of a few dozen to a few hundred reported errors that you don’t have time or energy to deal with right now. 

More info about this concept:
https://phpstan.org/user-guide/baseline
https://github.com/phpmd/phpmd/pull/873

**Comment by sebastianbergmann** [comment]
Possible? Of course. But will not work on this. I would review, and potentially accept, a pull request, though.

**Comment by bytestream** [comment]
Not as neat as a built-in solution, but I'm using https://github.com/DaveLiddament/sarb via https://github.com/supportpal/phpcpd2sarb - meets my needs.
