### ISSUE TITLE
Which algorithm is used in phpcpd?

### ISSUE THREAD

**Issue by olleharstedt** [sebastianbergmann/phpcpd#196]
Wikipedia mentions multiple algorithms to detect code duplication:

*    Baker's algorithm.[7]
 *   Rabin–Karp string search algorithm.
  *  Using Abstract Syntax Trees.[8]
  *  Visual clone detection.[9]
  *  Count Matrix Clone Detection.[10][11]
  *  Locality-sensitive hashing
   * Anti-unification[12]

https://en.wikipedia.org/wiki/Duplicate_code#Detecting_duplicate_code

Would be nice if the algorithm used in phpcpd was mentioned in the readme file.

**Comment by sebastianbergmann** [comment]
I did not implement the algorithm myself, @johannhartmann did that. I only built CLI tool around it. All I can tell you is that the algorithm operates on token streams, and not on the abstract syntax tree, for instance.
