### ISSUE TITLE
Is Apache 2.0 compatible with your license?

### ISSUE THREAD

**Issue by olleharstedt** [sebastianbergmann/phpcpd#198]
I'd like to merge a new algorithm which has license Apache 2.0. Is that license compatible with your current license? In Wikipedia they mention that Apache 2.0 is compatible with GPL v3 but not GPL v2.

https://en.wikipedia.org/wiki/Apache_License

**Comment by sebastianbergmann** [comment]
IANAL, but algorithms are not subject to an Open Source license.

**Comment by olleharstedt** [comment]
True, but the code would be basically copy-pasted, or manually transpiled from Java to PHP in a more or less 1-to-1 matter. I'm using their published code, not the pseudo-code as described in their paper.

**Comment by sebastianbergmann** [comment]
IANAL, again, sorry, but AFAIK Apache and BSD are compatible. When in doubt, ask who wrote the original code if they are okay with what you want to do.

**Comment by olleharstedt** [comment]
Oh, so phpcpd license is BSD? Good info! :) Yes, will try again to get in touch with the original authors.
