### ISSUE TITLE
Get warnings instead of errors

### ISSUE THREAD

**Issue by jigarius** [sebastianbergmann/phpcpd#204]
At the moment, `phpcpd` exists with error output. However, I'd like `phpcpd` to just issue warnings instead. Is that possible?

I'm using `phpcpd` with `grumphp`.

Any help/tips will be appreciated.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by jigarius** [comment]
Oops. I know this is not a support forum. My primary objective is to know this feature exists. Because I couldn't find anything related to severity or warnings on the project's readme page.

So to simplify my request further, is it possible to make phpcpd return warnings and exit with a 0 instead of returning errors and exiting with a non-zero?
