### ISSUE TITLE
How to define the most strict configuration possible for  phpcpd  ?

### ISSUE THREAD

**Issue by vic131** [sebastianbergmann/phpcpd#208]
I’m collaborating in a opensource project :

https://bitbucket.org/AliasAPI/damnp/src/master/etc/phpcpd/run_phpcpd.sh

And i am finding trouble configuring phpcpd  in the most sensitive way possible, so it would detected every generally undesired line of code. If anyone has any tips, it would be very welcome.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
