### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by fulldecent** [sebastianbergmann/phpcpd#82]
Hello, looking for build instructions on how to use this package to make the usable file. README.md shows how to install from another source.

**Comment by sebastianbergmann** [comment]
* `ant composer` downloads the dependencies and afterwards the `phpcpd` script is "usable"
* `ant phar` downloads the dependencies and afterwards builds a PHP Archive (PHAR)

**Comment by fulldecent** [comment]
Great, thank you.
