### ISSUE TITLE
--exclude is not working properly and not documented

### ISSUE THREAD

**Issue by vemod** [sebastianbergmann/phpcpd#84]
consider  `src/tests`, `src/something/deeper/tests`

`phpcpd --exclude tests src/`

will exclude not only `src/tests` but all occurrences of tests, means `src/something/deeper/tests` also will be excluded. 

Spent already an hour trying to figure out how to exclude `src/tests`,  but not `src/something/deeper/tests/`

I tried absalute path, relative path, path patterns, with quotes, without quotes etc.. none of the ways lets me do that. 

```
phpcpd 1.4.3 by Sebastian Bergmann.

Usage: phpcpd [switches] <directory|file> ...
...
  --exclude <dir>          Exclude <dir> from code analysis.
```

Sad that Sebastian Bergmann has so poorly documented this tool.

**Comment by jian-wu** [comment]
Hi guys, any update on a fix for this?  Thanks.

**Comment by sebastianbergmann** [comment]
Should have been taken care of by #100.
