### ISSUE TITLE
PHP Fatal error: Call to undefined function json_encode()

### ISSUE THREAD

**Issue by zot24** [sebastianbergmann/phpcpd#91]
Just after install it and run it like: 

```
$phpcpd
```

I'm seeing the following error:

```
PHP Fatal error:  Call to undefined function Symfony\Component\Console\Descriptor\json_encode() in phar:///usr/local/bin/phpcpd/symfony/console/Symfony/Component/Console/Descriptor/TextDescriptor.php on line 193
```

**Comment by emfluenceindia** [comment]
Hi, not sure if this is the right place to put my issue. I am an absolute newbie to PHP world.

I installed php using `phpbrew` on Ubuntu 14.04 and switched to version php-5.3.29 (`phpbrew switch php-5.3.29`). Then I went ahead to install JSON extension using `phpbrew ext install json` ([](https://github.com/phpbrew/phpbrew/wiki/Extension-Installer)).  But I ended up with the following:

`===> Installing json extension...
Log stored at: /home/subrara/.phpbrew/build/php-5.3.29/ext/json/build.log
Changing directory to /home/subrara/.phpbrew/build/php-5.3.29/ext/json
===> Running make clean: /usr/bin/make -C '/home/subrara/.phpbrew/build/php-5.3.29/ext/json' --quiet 'clean'
===> Phpize...
===> Configuring...
===> Building...
===> Running make all: /usr/bin/make -C '/home/subrara/.phpbrew/build/php-5.3.29/ext/json' 'all'  >> '/home/subrara/.phpbrew/build/php-5.3.29/ext/json/build.log' 2>&1
===> Installing...
===> Running make install: /usr/bin/make -C '/home/subrara/.phpbrew/build/php-5.3.29/ext/json' 'install'  >> '/home/subrara/.phpbrew/build/php-5.3.29/ext/json/build.log' 2>&1
===> Extension is installed.
===> Creating config file /home/subrara/.phpbrew/php/php-5.3.29/var/db/json.ini.disabled
PHP Warning:  mkdir(): Permission denied in phar:///usr/bin/phpbrew/src/PhpBrew/Extension/ExtensionManager.php on line 95

Warning: mkdir(): Permission denied in phar:///usr/bin/phpbrew/src/PhpBrew/Extension/ExtensionManager.php on line 95
PHP Warning:  file_put_contents(/home/subrara/.phpbrew/php/php-5.3.29/var/db/json.ini.disabled): failed to open stream: No such file or directory in phar:///usr/bin/phpbrew/src/PhpBrew/Extension/ExtensionManager.php on line 109

Warning: file_put_contents(/home/subrara/.phpbrew/php/php-5.3.29/var/db/json.ini.disabled): failed to open stream: No such file or directory in phar:///usr/bin/phpbrew/src/PhpBrew/Extension/ExtensionManager.php on line 109
===> Enabling extension json
json extension is not installed. Suggestions:
	$ phpbrew ext install json`

The reason I tried to install the extension is the following error message:

> Fatal error: Call to undefined function json_encode() in /var/www/app.com/app.main.drupal/includes/common.inc on line 2563

First I put my question at [](http://stackoverflow.com/questions/37919164/call-to-undefined-function-json-encode-drupal-site-setup-on-ubuntu-14-04-and-p) and got the idea of installing extension using `phpbrew ext install json`.

Even after I restarted HTTP server using `sudo service apache2 restart` application is still giving me the same error. Please help me to understand what I am doing wrong. Trying a things for a while now without any luck! :(
