### ISSUE TITLE
PHPCPD : Allowed memory size Issue

### ISSUE THREAD

**Issue by madhurtandon** [sebastianbergmann/phpcpd#96]
Memory limit in my php.ini file is 2048. i think it is sufficient.

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 71 bytes) in phar:///usr/local/bin/phpcpd/src/Detector/Strategy/Default.php on line 78

**Comment by tobegit3hub** [comment]
That helps and thanks @sebastianbergmann :smiley:
