### ISSUE TITLE
Annotation to suppress code checking for several lines / whole File

### ISSUE THREAD

**Issue by sneps85** [sebastianbergmann/phpcpd#99]
Could you add an annotation option to make it possible to disable CPD for:
- a whole file (@SuppressWarnings(PHPCPD) over class body)
  -a whole method (@SuppressWarnings(PHPCPD) over method body) 
- several lines of code (@SuppressWarnings(PHPCPD-START) and @SuppressWarnings(PHPCPD-END))

**Comment by nurikabe** [comment]
+1

**Comment by mi5ha** [comment]
Here is another scenario where this should be useful. When you use **annotations**.

For example APIs in Symfony are described with annotations on methods. So code itself is often times the same.

Without something like @SuppressWarnings, the only option is to manually exclude files/folders, which can add up.

**Comment by exuperok** [comment]
+1

**Comment by HectorOrdonez** [comment]
I do think this is a good idea. Please reconsider.

**Comment by Skippy565** [comment]
+1 definitely think this is a good idea.  While php does not support multiple inheritance some some people (myself included) iffy on utilizing traits, sometimes code reuse is required that throws cpd warnings.  (also almost every other tool has this ability - phpunit, phpmd, phpcs)

**Comment by jkanape** [comment]
+1

**Comment by renanmpimentel** [comment]
+10000

**Comment by Afinogen** [comment]
+1

**Comment by finalJustize** [comment]
+1

**Comment by KevinXL** [comment]
+1

**Comment by Knallcharge** [comment]
+1

**Comment by aabraham88** [comment]
+1

**Comment by Benjaminhu** [comment]
+1

Detects duplication in my test code (I got here because of a possible annotation search!):

```
	private function getExpectedDbPrivilegesAfterAdd()
	{
		return [
			['privilege_id' => '1', 'status' => '1'],
			['privilege_id' => '3', 'status' => '1'],
			['privilege_id' => '4', 'status' => '1'],
			['privilege_id' => '5', 'status' => '1'],
			['privilege_id' => '12', 'status' => '1'],
			['privilege_id' => '13', 'status' => '1'],
			['privilege_id' => '14', 'status' => '1'],
			['privilege_id' => '15', 'status' => '1'],
			['privilege_id' => '16', 'status' => '1'],
			['privilege_id' => '17', 'status' => '1'],
			['privilege_id' => '284', 'status' => '-1'],
			['privilege_id' => '285', 'status' => '-1'],
			['privilege_id' => '286', 'status' => '-1'],
			['privilege_id' => '287', 'status' => '-1'],
			['privilege_id' => '288', 'status' => '-1'],
			['privilege_id' => '290', 'status' => '-1'],
			['privilege_id' => '291', 'status' => '-1'],
			['privilege_id' => '292', 'status' => '-1'],
			['privilege_id' => '293', 'status' => '-1'],
			['privilege_id' => '294', 'status' => '-1'],
			['privilege_id' => '611', 'status' => '1'],
			['privilege_id' => '612', 'status' => '1'],
			['privilege_id' => '623', 'status' => '1'],
			['privilege_id' => '624', 'status' => '1'],
			['privilege_id' => '625', 'status' => '1'],
			['privilege_id' => '628', 'status' => '1']
		];
	}

	private function getExpectedDbPrivilegesAfterRemove()
	{
		return [
			['privilege_id' => '1', 'status' => '1'],
			['privilege_id' => '3', 'status' => '-1'],
			['privilege_id' => '4', 'status' => '-1'],
			['privilege_id' => '5', 'status' => '-1'],
			['privilege_id' => '12', 'status' => '1'],
			['privilege_id' => '13', 'status' => '1'],
			['privilege_id' => '14', 'status' => '1'],
			['privilege_id' => '15', 'status' => '1'],
			['privilege_id' => '16', 'status' => '1'],
			['privilege_id' => '17', 'status' => '1'],
			['privilege_id' => '284', 'status' => '-1'],
			['privilege_id' => '285', 'status' => '-1'],
			['privilege_id' => '286', 'status' => '-1'],
			['privilege_id' => '287', 'status' => '-1'],
			['privilege_id' => '288', 'status' => '-1'],
			['privilege_id' => '290', 'status' => '-1'],
			['privilege_id' => '291', 'status' => '-1'],
			['privilege_id' => '292', 'status' => '-1'],
			['privilege_id' => '293', 'status' => '-1'],
			['privilege_id' => '294', 'status' => '-1'],
			['privilege_id' => '611', 'status' => '1'],
			['privilege_id' => '612', 'status' => '1'],
			['privilege_id' => '623', 'status' => '1'],
			['privilege_id' => '624', 'status' => '1'],
			['privilege_id' => '625', 'status' => '1'],
			['privilege_id' => '628', 'status' => '1']
		];
	}
```

**Comment by mathieu-cda** [comment]
+1

**Comment by lennartvava** [comment]
+1

**Comment by lennartvava** [comment]
**Ignore should always be an option.** We often need to stop using phpcpd because of duplicate code which is required to have. In our case the problem occurs when we define a database schema in Drupal and later on we add an update hook to change this schema. Both the original schema array and the update hook function need to contain duplicate code. One should never call the other. More information on that here: https://www.drupal.org/node/150220

At least let the developer decide what should be ignored and what not. Please reconsider.

**Comment by victortodoran** [comment]
+1

**Comment by alessiodebernardi** [comment]
+1

**Comment by pczerkas** [comment]
+1

**Comment by imanzuk** [comment]
+1

**Comment by finalJustize** [comment]
+1

**Comment by sclubricants** [comment]
+1

**Comment by sclubricants** [comment]
How about something like 
// @CPDIGNORE NEXT 5
line1
line2
line3
line4
line5

**Comment by HLeithner** [comment]
+1

**Comment by kaurov** [comment]
For me, the solution is for now to split function into multiple smaller subfunction:
* SQL query generation uses `getSomething()` functions which can be overwritten in child classes
* Doctrine useges modify object using `setCondition() `@tzikis 
* array generation make `return array_merge($this->getPart1(), getPart2())`  @Benjaminhu 
* etc.

But yes, in general, I would like to have the ability to suppress such warnings using the annotation
